"use client";

import { useState } from "react";
import { ArrowUpRight, Plus, Minus } from "lucide-react";
import type { DemoLang } from "@/demos/config";
import { DemoNav } from "@/demos/shared/DemoNav";
import { DemoForm } from "@/demos/shared/DemoForm";
import { Architecture } from "@/demos/realestate-sukn/Architecture";
import type { Property } from "@/demos/realestate-sukn/content";
import { architectureContent } from "./content";

export function ArchitectureSite({ lang }: { lang: DemoLang }) {
  const t = architectureContent[lang];
  const [filter, setFilter] = useState(0);
  const [open, setOpen] = useState<string | null>(null);
  const [view, setView] = useState(0);
  return (
    <div id="top">
      <DemoNav site="architecture" lang={lang} brand={<span className="flex items-baseline gap-3"><strong className="text-3xl font-bold tracking-[-.08em]">{t.brand}<span className="text-d-accent">.</span></strong><span className="hidden text-[10px] sm:block">{t.sub}</span></span>} links={t.nav.map((label, i) => ({ label, href: ["#work", "#practice", "#contact"][i] }))} className="border-b border-d-line bg-d-bg/95" panelClassName="bg-d-bg" langClassName="border-d-line" toggleClassName="border-d-line" />
      <main>
        <section className="container-d pt-32 pb-14 sm:pt-40"><div className="flex flex-wrap items-center justify-between gap-3 text-[10px] font-medium tracking-widest"><p>{t.eyebrow}</p><p>{t.year}</p></div><div className="mt-10 grid gap-8 lg:grid-cols-[1.3fr_.7fr] lg:items-end"><h1 className="text-6xl font-medium leading-[1.08] tracking-[-.065em] sm:text-8xl lg:text-[6.7rem]">{t.title}<br />{t.accent}</h1><div className="max-w-sm lg:pb-3"><p className="text-base leading-relaxed text-d-muted">{t.text}</p><a href="#work" className="mt-7 inline-flex items-center gap-8 border-b border-d-fg pb-2 text-sm font-medium">{t.cta}<ArrowUpRight className="size-5" /></a></div></div><div className="mt-12 overflow-hidden bg-[#DADCCE]"><Architecture property={{ type: "villa", tone: "sand" }} className="max-h-[540px] w-full object-cover" label={t.imageLabel} /></div><div className="mt-4 flex flex-wrap justify-between gap-2 text-xs"><strong>{t.heroName}</strong><span className="text-d-muted">{t.heroMeta}</span></div></section>
        <section id="work" className="container-d py-12 sm:py-20"><div className="grid gap-6 border-t border-d-fg pt-7 sm:grid-cols-2"><h2 className="text-4xl font-medium tracking-tight">{t.workTitle}</h2><p className="max-w-md text-sm leading-relaxed text-d-muted">{t.workText}</p></div><div className="my-8 flex flex-wrap gap-5" role="group" aria-label={t.nav[0]}>{t.filters.map((label, i) => <button key={label} aria-pressed={filter === i} onClick={() => { setFilter(i); setOpen(null); }} className={`border-b py-2 text-sm ${filter === i ? "border-d-accent text-d-accent" : "border-transparent text-d-muted"}`}>{label}</button>)}</div><div className="grid items-start gap-x-8 gap-y-12 md:grid-cols-2">{t.projects.filter((project) => !filter || project.category === filter).map((project, i) => <article key={project.id} className={i === 0 && filter === 0 ? "md:col-span-2" : ""}><div className="overflow-hidden bg-d-surface"><Architecture property={{ type: project.type, tone: project.tone } as Pick<Property, "type" | "tone">} view={open === project.id ? view : 0} label={`${project.title} · ${t.views[open === project.id ? view : 0]}`} className={`w-full ${i === 0 && filter === 0 ? "max-h-[540px]" : ""}`} /></div><div className="flex items-start justify-between gap-4 pt-4"><div><p className="mb-1 text-[10px] uppercase tracking-wider text-d-muted">{t.filters[project.category]} / {project.location}</p><h3 className="text-2xl font-medium">{project.title}</h3></div><button onClick={() => { setOpen(open === project.id ? null : project.id); setView(0); }} aria-expanded={open === project.id} aria-controls={`study-${project.id}`} aria-label={`${open === project.id ? t.close : t.details}: ${project.title}`} className="grid size-11 shrink-0 place-items-center rounded-full border border-d-line hover:border-d-fg">{open === project.id ? <Minus className="size-5" /> : <Plus className="size-5" />}</button></div>{open === project.id && <div id={`study-${project.id}`} className="mt-5 border-t border-d-line pt-5"><div className="mb-5 flex flex-wrap gap-2" role="group" aria-label={t.details}>{t.views.map((label, index) => <button key={label} onClick={() => setView(index)} aria-pressed={view === index} className={`border px-4 py-2 text-xs ${view === index ? "border-d-fg bg-d-fg text-d-bg" : "border-d-line"}`}>{label}</button>)}</div><p className="max-w-2xl text-sm leading-relaxed text-d-muted">{project.text}</p><dl className="mt-5 grid gap-4 text-xs sm:grid-cols-3">{[[t.location, project.location], [t.area, project.area], [t.materials, project.materials]].map(([label, value]) => <div key={label}><dt className="text-d-muted">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</dl></div>}</article>)}</div><p className="mt-8 text-xs text-d-muted">{t.illustrationNote}</p></section>
        <section id="practice" className="bg-d-fg py-16 text-d-bg sm:py-24"><div className="container-d"><div className="grid gap-8 lg:grid-cols-2"><p className="text-xs">02 / {t.nav[1]}</p><div><h2 className="max-w-lg text-4xl leading-tight sm:text-5xl">{t.practiceTitle}</h2><p className="mt-6 max-w-lg leading-relaxed opacity-70">{t.practiceText}</p></div></div><div className="mt-14 grid gap-8 md:grid-cols-3">{t.process.map((step, i) => <div key={step.title} className="border-t border-white/25 pt-6"><span className="text-xs opacity-50">0{i + 1}</span><h3 className="mt-5 text-xl">{step.title}</h3><p className="mt-3 text-sm leading-relaxed opacity-70">{step.text}</p></div>)}</div></div></section>
        <section id="contact" className="container-d grid gap-12 py-16 sm:py-24 lg:grid-cols-2"><div><p className="text-xs">03 / {t.nav[2]}</p><h2 className="mt-6 max-w-md text-4xl leading-tight sm:text-5xl">{t.contactTitle}</h2><p className="mt-6 max-w-md leading-relaxed text-d-muted">{t.contactText}</p></div><DemoForm fields={[{ name: "name", label: t.name, half: true }, { name: "email", label: t.email, type: "email", half: true }, { name: "project", label: t.project, type: "select", options: t.filters.slice(1) }, { name: "message", label: t.message, type: "textarea" }]} submit={t.submit} success={t.success} note={t.note} inputClassName="!rounded-none border-d-line bg-transparent" buttonClassName="!rounded-none bg-d-fg text-d-bg" /></section>
      </main>
      <footer className="container-d flex flex-wrap justify-between gap-5 border-t border-d-line py-8 pb-28 text-xs"><span>{t.brand} · {t.footer}</span><a href="#top" className="underline underline-offset-4">{t.top}</a></footer>
    </div>
  );
}
